#!/usr/bin/env python3
"""Cross-data consistency audit for crystallographic point-group JSON files.

This script intentionally checks invariants that are not covered, or are only
partially covered, by validate.py:

* every actual subgroup generated by the Cayley table is listed in JSON;
* normal-subgroup quotient_group labels are isomorphic to the actual quotient;
* abelianization labels match G/[G,G];
* geometric hints (axis, plane_normal, rotation_angle_deg) agree with matrices.

It uses only the Python standard library so that it can run in minimal
environments where numpy/pytest are unavailable.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
TOL = 1e-6


@dataclass(frozen=True)
class Finding:
    severity: str
    group: str
    check: str
    message: str


def load_groups() -> dict[str, dict]:
    groups: dict[str, dict] = {}
    for path in sorted(DATA_DIR.glob("[0-9][0-9]_*.json")):
        with path.open(encoding="utf-8") as f:
            raw = json.load(f)
        groups[raw["schoenflies"]] = raw
    return groups


def multiply(group: dict, i: int, j: int) -> int:
    return int(group["multiplication_table"][i][j])


def vec_dot(a: Iterable[float], b: Iterable[float]) -> float:
    return sum(x * y for x, y in zip(a, b))


def vec_sub(a: Iterable[float], b: Iterable[float]) -> list[float]:
    return [x - y for x, y in zip(a, b)]


def vec_add(a: Iterable[float], b: Iterable[float]) -> list[float]:
    return [x + y for x, y in zip(a, b)]


def vec_neg(a: Iterable[float]) -> list[float]:
    return [-x for x in a]


def vec_norm(a: Iterable[float]) -> float:
    values = list(a)
    return math.sqrt(vec_dot(values, values))


def close_vec(a: Iterable[float], b: Iterable[float], tol: float = TOL) -> bool:
    return vec_norm(vec_sub(a, b)) <= tol


def mat_vec_mul(matrix: list[list[float]], vector: list[float]) -> list[float]:
    return [sum(row[k] * vector[k] for k in range(3)) for row in matrix]


def mat_trace(matrix: list[list[float]]) -> float:
    return sum(matrix[i][i] for i in range(3))


def generated_subgroup(group: dict, generators: Iterable[int]) -> frozenset[int]:
    subgroup = set(generators) | {0}
    changed = True
    while changed:
        changed = False
        current = list(subgroup)
        for a in current:
            for b in current:
                product = multiply(group, a, b)
                if product not in subgroup:
                    subgroup.add(product)
                    changed = True
    return frozenset(subgroup)


def enumerate_subgroups(group: dict) -> set[frozenset[int]]:
    """Enumerate all subgroups by repeatedly adjoining one generator."""
    subgroups = {frozenset({0})}
    changed = True
    while changed:
        changed = False
        for subgroup in list(subgroups):
            for element in range(group["order"]):
                generated = generated_subgroup(group, set(subgroup) | {element})
                if generated not in subgroups:
                    subgroups.add(generated)
                    changed = True
    return subgroups


def left_cosets(group: dict, subgroup: Iterable[int]) -> list[frozenset[int]]:
    remaining = set(range(group["order"]))
    subgroup_set = set(subgroup)
    cosets: list[frozenset[int]] = []
    while remaining:
        representative = min(remaining)
        coset = frozenset(multiply(group, representative, h) for h in subgroup_set)
        cosets.append(coset)
        remaining -= set(coset)
    return cosets


def quotient_table(group: dict, subgroup: Iterable[int]) -> list[list[int]]:
    cosets = left_cosets(group, subgroup)
    representatives = [min(coset) for coset in cosets]

    def coset_index(element: int) -> int:
        for idx, coset in enumerate(cosets):
            if element in coset:
                return idx
        raise ValueError(f"element {element} is not in any coset")

    return [
        [coset_index(multiply(group, a, b)) for b in representatives]
        for a in representatives
    ]


def element_orders_from_table(table: list[list[int]]) -> list[int]:
    orders = []
    for element in range(len(table)):
        current = 0
        for power in range(1, len(table) + 1):
            current = table[current][element]
            if current == 0:
                orders.append(power)
                break
        else:
            raise ValueError(f"element {element} never returned to identity")
    return orders


def tables_are_isomorphic(left: list[list[int]], right: list[list[int]]) -> bool:
    """Small-group isomorphism test with identity fixed at index 0."""
    n = len(left)
    if len(right) != n:
        return False
    if left == right:
        return True

    left_orders = element_orders_from_table(left)
    right_orders = element_orders_from_table(right)
    if sorted(left_orders) != sorted(right_orders):
        return False

    candidates = {
        i: [j for j in range(n) if right_orders[j] == left_orders[i]]
        for i in range(n)
    }
    mapping = {0: 0}
    used = {0}
    search_order = sorted(range(1, n), key=lambda i: len(candidates[i]))

    def partial_homomorphism_ok() -> bool:
        for a, mapped_a in mapping.items():
            for b, mapped_b in mapping.items():
                product = left[a][b]
                mapped_product = right[mapped_a][mapped_b]
                if product in mapping and mapping[product] != mapped_product:
                    return False
                if product not in mapping and mapped_product in used:
                    return False
        return True

    def backtrack(position: int) -> bool:
        if position == len(search_order):
            return partial_homomorphism_ok()
        source = search_order[position]
        for target in candidates[source]:
            if target in used:
                continue
            mapping[source] = target
            used.add(target)
            if partial_homomorphism_ok() and backtrack(position + 1):
                return True
            used.remove(target)
            del mapping[source]
        return False

    return backtrack(0)


def format_set(values: Iterable[int]) -> str:
    return "{" + ", ".join(str(v) for v in sorted(values)) + "}"


def audit_subgroup_completeness(group: dict) -> list[Finding]:
    actual = enumerate_subgroups(group)
    declared = {frozenset(s["element_indices"]) for s in group["subgroups"]}
    findings: list[Finding] = []
    for subgroup in sorted(actual - declared, key=lambda s: (len(s), sorted(s))):
        findings.append(
            Finding(
                "ERROR",
                group["schoenflies"],
                "subgroup_completeness",
                f"actual subgroup {format_set(subgroup)} is not listed",
            )
        )
    for subgroup in sorted(declared - actual, key=lambda s: (len(s), sorted(s))):
        findings.append(
            Finding(
                "ERROR",
                group["schoenflies"],
                "subgroup_completeness",
                f"listed subgroup {format_set(subgroup)} is not closed/generated",
            )
        )
    return findings


def audit_quotients(group: dict, groups: dict[str, dict]) -> list[Finding]:
    findings: list[Finding] = []
    for subgroup in group["subgroups"]:
        quotient_name = subgroup.get("quotient_group")
        if not subgroup.get("is_normal") or quotient_name is None:
            continue
        if quotient_name not in groups:
            findings.append(
                Finding(
                    "ERROR",
                    group["schoenflies"],
                    "quotient_group",
                    f"{subgroup['schoenflies']} names unknown quotient {quotient_name!r}",
                )
            )
            continue
        actual = quotient_table(group, subgroup["element_indices"])
        expected = groups[quotient_name]["multiplication_table"]
        if len(actual) != groups[quotient_name]["order"]:
            findings.append(
                Finding(
                    "ERROR",
                    group["schoenflies"],
                    "quotient_group",
                    f"{subgroup['schoenflies']} quotient has order {len(actual)}, "
                    f"but {quotient_name} has order {groups[quotient_name]['order']}",
                )
            )
        elif not tables_are_isomorphic(actual, expected):
            findings.append(
                Finding(
                    "ERROR",
                    group["schoenflies"],
                    "quotient_group",
                    f"{subgroup['schoenflies']} quotient is not isomorphic to "
                    f"{quotient_name}",
                )
            )
    return findings


def audit_abelianization(group: dict, groups: dict[str, dict]) -> list[Finding]:
    name = group.get("abelianization")
    commutator = group.get("commutator_subgroup")
    if not name or commutator is None:
        return []
    if name not in groups:
        return [
            Finding(
                "ERROR",
                group["schoenflies"],
                "abelianization",
                f"abelianization names unknown group {name!r}",
            )
        ]
    actual = quotient_table(group, commutator)
    expected = groups[name]["multiplication_table"]
    if len(actual) != groups[name]["order"]:
        return [
            Finding(
                "ERROR",
                group["schoenflies"],
                "abelianization",
                f"G/[G,G] has order {len(actual)}, but {name} has order "
                f"{groups[name]['order']}",
            )
        ]
    if not tables_are_isomorphic(actual, expected):
        return [
            Finding(
                "ERROR",
                group["schoenflies"],
                "abelianization",
                f"G/[G,G] is not isomorphic to declared {name}",
            )
        ]
    return []


def audit_geometry_hints(group: dict) -> list[Finding]:
    findings: list[Finding] = []
    for element in group["elements"]:
        matrix = element["matrix"]
        idx = element["index"]
        symbol = element["schoenflies"]
        elem_type = element["type"]

        axis = element.get("axis")
        if axis is not None:
            image = mat_vec_mul(matrix, axis)
            if elem_type == "rotation" and not close_vec(image, axis):
                findings.append(
                    Finding(
                        "ERROR",
                        group["schoenflies"],
                        "axis_geometry",
                        f"g_{idx} {symbol}: axis {axis} is not fixed by matrix "
                        f"(M axis = {image})",
                    )
                )
            if elem_type == "improper_rotation":
                axis_like = close_vec(image, axis) or close_vec(image, vec_neg(axis))
                if not axis_like:
                    findings.append(
                        Finding(
                            "ERROR",
                            group["schoenflies"],
                            "axis_geometry",
                            f"g_{idx} {symbol}: axis {axis} is not an eigenvector "
                            f"of improper-rotation matrix (M axis = {image})",
                        )
                    )

        normal = element.get("plane_normal")
        if normal is not None and elem_type == "reflection":
            image = mat_vec_mul(matrix, normal)
            if not close_vec(image, vec_neg(normal)):
                findings.append(
                    Finding(
                        "ERROR",
                        group["schoenflies"],
                        "plane_normal_geometry",
                        f"g_{idx} {symbol}: plane_normal {normal} is not the "
                        f"-1 eigenvector of the reflection matrix (M n = {image})",
                    )
                )

        if elem_type == "rotation" and idx != 0 and element.get("rotation_angle_deg") is not None:
            cos_angle = max(-1.0, min(1.0, (mat_trace(matrix) - 1.0) / 2.0))
            actual = math.degrees(math.acos(cos_angle))
            declared = float(element["rotation_angle_deg"]) % 360.0
            declared_unsigned = min(declared, 360.0 - declared)
            if abs(actual - declared_unsigned) > 1e-5:
                findings.append(
                    Finding(
                        "ERROR",
                        group["schoenflies"],
                        "rotation_angle",
                        f"g_{idx} {symbol}: rotation_angle_deg={declared:g}, "
                        f"but matrix trace implies {actual:.6g} degrees",
                    )
                )
    return findings


def run_audit(groups: dict[str, dict]) -> list[Finding]:
    findings: list[Finding] = []
    for group in groups.values():
        findings.extend(audit_subgroup_completeness(group))
        findings.extend(audit_quotients(group, groups))
        findings.extend(audit_abelianization(group, groups))
        findings.extend(audit_geometry_hints(group))
    return findings


def render_markdown(groups: dict[str, dict], findings: list[Finding]) -> str:
    lines = [
        "# Consistency Audit Report",
        "",
        "## Scope",
        "",
        f"- Audited {len(groups)} point-group JSON files in `data/`.",
        "- The audit script does not modify JSON files.",
        "- The audit focuses on cross-file and semantic checks that go beyond the existing pytest/validate.py checks.",
        "",
        "## Additional Checks",
        "",
        "- Exhaustive subgroup enumeration from each multiplication table versus declared `subgroups`.",
        "- Actual quotient group `G/H` for every declared normal subgroup versus the named `quotient_group`.",
        "- Actual abelianization `G/[G,G]` versus the declared `abelianization` group.",
        "- Matrix compatibility of geometric hints: rotation axes, reflection plane normals, and rotation angles.",
        "",
        "## Findings",
        "",
    ]
    if not findings:
        lines.append("No inconsistencies were found by the additional audit.")
    else:
        for finding in findings:
            lines.append(
                f"- **{finding.severity}** `{finding.group}` "
                f"`{finding.check}`: {finding.message}"
            )
    if any(f.check == "plane_normal_geometry" for f in findings):
        lines.extend(
            [
                "",
                "## Interpretation",
                "",
                "- For a reflection, `plane_normal` should be the -1 eigenvector of the matrix.",
                "- The D4h findings have `M n = n`, so the stored vector lies in the mirror plane rather than normal to it.",
                "- In `data/15_D4h.json`, the two diagonal mirror normals appear to be swapped: g_14 should use a vector parallel to `[1, 1, 0]`, while g_15 should use a vector parallel to `[1, -1, 0]`.",
            ]
        )
    lines.extend(
        [
            "",
            "## Summary",
            "",
            f"- Findings: {len(findings)}",
            f"- Groups with findings: {len({f.group for f in findings})}",
            "",
            "## Reproduction",
            "",
            "```bash",
            "python3 scripts/audit_consistency.py --write-report audit_report.md",
            "```",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Audit point-group JSON consistency")
    parser.add_argument(
        "--write-report",
        metavar="PATH",
        help="write a Markdown report to PATH",
    )
    args = parser.parse_args()

    groups = load_groups()
    findings = run_audit(groups)
    markdown = render_markdown(groups, findings)
    if args.write_report:
        Path(args.write_report).write_text(markdown, encoding="utf-8")
    print(markdown)
    return 1 if findings else 0


if __name__ == "__main__":
    raise SystemExit(main())
